name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create required directories
        run: |
          mkdir -p lib bin src test

      - name: Download Dependencies
        run: |
          curl -L https://repo1.maven.org/maven2/org/jfree/jcommon/1.0.17/jcommon-1.0.17.jar -o lib/jcommon-1.0.17.jar
          curl -L https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1.jar -o lib/javax.servlet-api-3.0.1.jar

      - name: Compile Source Files
        run: |
          echo "Checking for Java files in src directory..."
          find src -type f -name "*.java" -print
          if [ -z "$(find src -type f -name '*.java' 2>/dev/null)" ]; then echo "No source files found, skipping compilation."; else javac -d bin -cp "bin:lib/*" $(find src -type f -name "*.java"); fi

      - name: Compile Test Files
        run: |
          if [ -z "$(find test/ -name '*.java' 2>/dev/null)" ]; then echo "No test files found, skipping compilation."; else javac -d bin -cp "bin:lib/*" test/Test1.java test/Test2.java test/Test3.java; fi

      - name: Run Tests
        run: |
          if [ -z "$(find bin/ -name '*.class' 2>/dev/null)" ]; then echo "No compiled classes found, skipping tests."; else java -jar lib/junit-platform-console-standalone-1.5.2.jar --class-path bin --scan-class-path; fi
